 Dataset:
     'dir' : "/mnt/"
     '2013-14' : "/mnt/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv"
     '2015' : "/mnt/Parking_Violations_Issued_-_Fiscal_Year_2015.csv"
     '2016' : "/mnt/Parking_Violations_Issued_-_Fiscal_Year_2016.csv"
     '2017' : "/mnt/Parking_Violations_Issued_-_Fiscal_Year_2017.csv"
 clean_data:
     'dir' : "/domino/datasets/local/qe_intelligent_workspaces/clean_data"
     '2013-14' : "/domino/datasets/local/qe_intelligent_workspaces/clean_data/clean_data_13_14.csv"
     '2015' : "/domino/datasets/local/qe_intelligent_workspaces/clean_data/clean_data_15.csv"
     '2016' : "/domino/datasets/local/qe_intelligent_workspaces/clean_data/clean_data_16.csv"
     '2017' : "/domino/datasets/local/qe_intelligent_workspaces/clean_data/clean_data_17.csv"
